version: '3.8'

services:
  load-balancer:
    build: 
      context: ./load-balancer
    environment:
      - PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - ALL_INSTANCES_IDS=INSTANCE_ID_1
    ports:
      - "5432:5432"
    depends_on:
      - redis
      - db_instance_1

  # proxy:
  #   build: 
  #     context: ./proxy
  #   environment:
  #     - PORT=5433
  #   ports:
  #     - "5433:5433"

  client:
    build:
      context: ./client
    environment:
      - DB_USER=your_username
      - DB_NAME=your_database
      - DB_HOST=load-balancer
      - DB_PASSWORD=your_password
      - DB_PORT=5432
    depends_on:
      - load-balancer

  db_instance_1:
    build:
        context: ./db-instance
    environment:
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_HOST=postgres_1
      - DB_PASSWORD=postgres
      - INSTANCE_ID=INSTANCE_ID_1
      - ALL_INSTANCES_IDS=INSTANCE_ID_1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - DB_PORT=5435
      - PORT=5555
    depends_on:
      - postgres_1
      - redis
    ports:
      - "5555:5555"

  postgres_1:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5435
    command: -p 5435
    ports:
      - "5435:5435"

  db_instance_2:
    build:
        context: ./db-instance
    environment:
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_HOST=postgres_2
      - DB_PASSWORD=postgres
      - INSTANCE_ID=INSTANCE_ID_2
      - ALL_INSTANCES_IDS=INSTANCE_ID_1,INSTANCE_ID_2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - DB_PORT=5436
      - PORT=5556
    depends_on:
      - postgres_1
      - redis
    ports:
      - "5556:5556"

  postgres_2:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5436
    command: -p 5436
    ports:
      - "5436:5436"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
